version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      # Install poetry
      - pip install poetry
    post_create_environment:
      # Configure poetry
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with poetry
      - poetry install --only docs
      # Install the package itself
      - poetry install --only-root

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
