version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --only docs --no-interaction
    # Install safe dependencies manually (needed for imports) but no janus_swi
    - pip install pydantic
    # Install your package without dependencies
    - pip install --no-deps -e .
    - python -m sphinx -T -b html -d _build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
