[mypy]
exclude = ^(tests\/test.*\.py|scripts\/.*\.py|docs\/.*\.py)$
python_version = 3.11
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
ignore_missing_imports = True
show_error_codes = True
warn_unused_ignores = True
