name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install SWI-Prolog
        run: |
          # Add PPA for latest SWI-Prolog
          sudo apt-add-repository ppa:swi-prolog/stable
          sudo apt-get update
          # Install SWI-Prolog
          sudo apt-get install -y swi-prolog
          # Verify version
          swipl --version
          # Get SWI-Prolog paths
          echo "Checking SWI-Prolog configuration..."
          swipl -g "current_prolog_flag(home, Home), writeln(Home)" -t halt
          swipl -g "current_prolog_flag(executable, Exe), writeln(Exe)" -t halt

      - name: Set up SWI-Prolog environment
        run: |
          # Get SWI-Prolog home directory
          SWIPL_HOME=$(swipl -g "current_prolog_flag(home, Home), writeln(Home)" -t halt)
          echo "SWI_HOME_DIR=$SWIPL_HOME" >> $GITHUB_ENV

          # Set library path
          ARCH=$(uname -m)
          echo "LD_LIBRARY_PATH=$SWIPL_HOME/lib/$ARCH-linux:$LD_LIBRARY_PATH" >> $GITHUB_ENV

          # Verify environment
          echo "SWI-Prolog environment:"
          echo "SWI_HOME_DIR: $SWIPL_HOME"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install Dependencies
        run: |
          # Update pip first
          poetry run pip install --upgrade pip
          # Install janus-swi separately first
          poetry run pip install janus-swi==1.5.2
          # Then install the rest
          poetry install --with docs --verbose

      - name: Debug Environment
        run: |
          poetry env info
          poetry show
          poetry check
          poetry run pip list
          poetry run sphinx-build --version
          which swipl
          swipl --version

      - name: Build Documentation
        run: |
          cd docs
          poetry run make SPHINXOPTS="-v" html
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          SPHINX_DEBUG: 1

      - name: Check Build Output
        if: always()
        run: |
          echo "Checking docs build directory..."
          cd docs/_build/html
          ls -la
          if [ -f "index.html" ]; then
            echo "Documentation built successfully"
          else
            echo "Documentation build failed - no index.html"
            exit 1
          fi

      - name: Run doc8
        if: always()
        run: |
          cd docs
          poetry run doc8 --config doc8.ini .

      - name: Upload Documentation Artifacts
        if: always()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: documentation
          path: docs/_build/html/
          compression-level: 0  # New option in v4

      - name: Trigger RTD build
        if: success()
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
